# Generated by Django 3.2.8 on 2021-10-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='ddk', unique=True, verbose_name='URL'),
        ),
    ]
