# Generated by Django 3.2.8 on 2021-11-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_recipe_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
